spring:
  datasource:
    url: jdbc:mysql://127.0.01:3306/corona?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  jpa:
#    hibernate.ddl-auto: update
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true